/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/profile/setup`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/add-exercise`; params?: Router.UnknownInputParams; } | { pathname: `/workouts`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/new`; params?: Router.UnknownInputParams; } | { pathname: `/exercises/[exerciseId]`, params: Router.UnknownInputParams & { exerciseId: string | number; } } | { pathname: `/progress/[exerciseId]`, params: Router.UnknownInputParams & { exerciseId: string | number; } } | { pathname: `/workouts/[workoutId]`, params: Router.UnknownInputParams & { workoutId: string | number; } } | { pathname: `/workouts/[workoutId]/session`, params: Router.UnknownInputParams & { workoutId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/exercises`; params?: Router.UnknownOutputParams; } | { pathname: `/history`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/setup`; params?: Router.UnknownOutputParams; } | { pathname: `/workouts/add-exercise`; params?: Router.UnknownOutputParams; } | { pathname: `/workouts`; params?: Router.UnknownOutputParams; } | { pathname: `/workouts/new`; params?: Router.UnknownOutputParams; } | { pathname: `/exercises/[exerciseId]`, params: Router.UnknownOutputParams & { exerciseId: string; } } | { pathname: `/progress/[exerciseId]`, params: Router.UnknownOutputParams & { exerciseId: string; } } | { pathname: `/workouts/[workoutId]`, params: Router.UnknownOutputParams & { workoutId: string; } } | { pathname: `/workouts/[workoutId]/session`, params: Router.UnknownOutputParams & { workoutId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgot-password${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `/exercises${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `/profile/setup${`?${string}` | `#${string}` | ''}` | `/workouts/add-exercise${`?${string}` | `#${string}` | ''}` | `/workouts${`?${string}` | `#${string}` | ''}` | `/workouts/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/profile/setup`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/add-exercise`; params?: Router.UnknownInputParams; } | { pathname: `/workouts`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/new`; params?: Router.UnknownInputParams; } | `/exercises/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/progress/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/workouts/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/workouts/${Router.SingleRoutePart<T>}/session${`?${string}` | `#${string}` | ''}` | { pathname: `/exercises/[exerciseId]`, params: Router.UnknownInputParams & { exerciseId: string | number; } } | { pathname: `/progress/[exerciseId]`, params: Router.UnknownInputParams & { exerciseId: string | number; } } | { pathname: `/workouts/[workoutId]`, params: Router.UnknownInputParams & { workoutId: string | number; } } | { pathname: `/workouts/[workoutId]/session`, params: Router.UnknownInputParams & { workoutId: string | number; } };
    }
  }
}
